name: encrypt
version: 4.0.2
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: ^1.6.0
  asn1lib: ^0.6.4
  clock: ^1.0.1
  collection: ^1.14.12
  crypto: ^2.1.4
  pointycastle:
    git: https://github.com/bcgit/pc-dart.git

dev_dependencies:
  test: ^1.14.3
